# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sniphpet
email: fdkhadra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Articles on Php, Javascript, web application in general
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sniphpet.com" # the base hostname & protocol for your site
enforce_ssl: sniphpet.com
github_username:  sniphpet
paginate: 8
paginate_path: "/page:num/"
sass:
  compressed: true
# Build settings
markdown: kramdown

# Gems
gems: [jekyll-paginate, jemoji, jekyll-sitemap]
